names <- c("A","B","C","D")
age <- c(1,2,3,4)
people <- data.frame(names, age)
head(people)
str(people)
glimpse(people)
colnames(people)
mutate(people, age_in_20 = age + 20)

name_fruits <- c("apple","banana","mango","watermalon","durian")
rank_fruits <- c(1, 2, 3, 4, 5)
fruits_rank <- data.frame(name_fruits, rank_fruits)
head(fruits_rank)
mutate(fruits_rank, rank_afterwards = rank_fruits + 10)
as_tibble(fruits_rank)
